# Generated by Django 2.1 on 2018-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_web', '0001_initial'),
    ]

    operations = [
        #migrations.AlterField(
        #    model_name='article',
        #    name='content',
        #    field=models.TextField(blank=True, default='', verbose_name='内容'),
        #),
    ]
